### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by annalynayop** [rossmartin/video-editor-ionic2#1]
Hi Good Day,
 I followed your instructions and tried to run this on android device, but I'm having an error..hope you can give me an idea for this..thanks
![error](https://cloud.githubusercontent.com/assets/8409364/16605367/e7de342e-4360-11e6-9554-2b882f707493.png)

**Comment by rossmartin** [comment]
The plugin for android requires android sdk version 18 (android 4.3) 

In your app's root config.xml add this below to your android preferences or create if needed - 

```
<platform name="android">
    ...
    <preference name="android-minSdkVersion" value="18" />
    ...
</platform>
```

**Comment by annalynayop** [comment]
yey it works.thanks :)
