### ISSUE TITLE
Error while running app

### ISSUE THREAD

**Issue by kalyandechiraju** [rossmartin/video-editor-ionic2#2]
Hi @rossmartin, I am facing this exception while on click event

EXCEPTION: Error during evaluation of "click"
ORIGINAL EXCEPTION: TypeError: undefined is not an object (evaluating 'navigator.device.capture')

Please help me in running this application. On device, the app is not responding to click of the ion-item.

**Comment by rossmartin** [comment]
Did you add the necessary plugins via step 5?

```
ionic plugin add cordova-plugin-camera cordova-plugin-device cordova-plugin-media-capture https://github.com/driftyco/ionic-plugin-keyboard.git cordova-plugin-statusbar cordova-plugin-spinner-dialog cordova-plugin-instagram-assets-picker cordova-plugin-video-editor
```

**Comment by kalyandechiraju** [comment]
Yes. Same error. Now while building for Android device, getting this error.

Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library [com.github.ergovia-mobile:android-transcoder:v0.1.10R_ergovia] /Users/kalyandechiraju/Downloads/video-editor-ionic2-master/platforms/android/build/intermediates/exploded-aar/com.github.ergovia-mobile/android-transcoder/v0.1.10R_ergovia/AndroidManifest.xml

**Comment by rossmartin** [comment]
The video editor plugin for android requires android sdk version 18 (android 4.3) 

In your app's root config.xml add this below to your android preferences or create if needed - 

```
<platform name="android">
    ...
    <preference name="android-minSdkVersion" value="18" />
    ...
</platform>
```

**Comment by kalyandechiraju** [comment]
Thank you @rossmartin . It worked. Can you help me out in doing the same with typescript? Typescript is complaining about device (Property 'device' does not exist on type 'Navigator').

navigator.**device**.capture.captureVideo

How to resolve this? Or is there any alternate way to use media-capture-plugin with typescript?

**Comment by kalyandechiraju** [comment]
Hey the above error I am facing was resolved by adding navigator global declaration  (In typescript)

`declare var navigator: any;`
